gateway = 'https://devnet-gateway.multiversx.com'
bump_address = "erd1qqqqqqqqqqqqqpgq8ry8k8vk70wwpsjyey7xk8f57qcmpadwa4sq5tcnf9"
coinflip_address = "erd1qqqqqqqqqqqqqpgqu7ym00xsszp2mf5dh3xz798rtqjz43jta4sqzpt82e"
gaspass_address = "erd1qqqqqqqqqqqqqpgqqx2l65rtymptmyzdaqyr9mmdpm5cgrxga4sqld6mrz"
